/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ui;

/**
 *
 * @author manojreddy
 */
public class DefaultJPanel extends javax.swing.JPanel {

    /**
     * Creates new form defaultJPanel
     */
    public DefaultJPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        systemjLabel = new javax.swing.JLabel();
        managejLabel = new javax.swing.JLabel();
        trackjLabel = new javax.swing.JLabel();

        systemjLabel.setFont(new java.awt.Font("Lucida Grande", 1, 24)); // NOI18N
        systemjLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        systemjLabel.setText("System Management");

        managejLabel.setFont(new java.awt.Font("Lucida Grande", 2, 14)); // NOI18N
        managejLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        managejLabel.setText("<<  Use the Manage Button on the Left Panel to update the System Model");

        trackjLabel.setFont(new java.awt.Font("Lucida Grande", 2, 14)); // NOI18N
        trackjLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        trackjLabel.setText("<<  Use the Track Button on the Left Panel to view Abnormal Persons");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(231, 231, 231)
                        .addComponent(systemjLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 268, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(96, 96, 96)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(trackjLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 540, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(managejLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 540, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(136, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addComponent(systemjLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(57, 57, 57)
                .addComponent(managejLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34)
                .addComponent(trackjLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(188, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel managejLabel;
    private javax.swing.JLabel systemjLabel;
    private javax.swing.JLabel trackjLabel;
    // End of variables declaration//GEN-END:variables
}
