/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ui;

import java.awt.CardLayout;
import java.util.List;
import javax.swing.JPanel;
import model.City;
import model.System;
import model.CityName;
import model.Community;

/**
 *
 * @author manojreddy
 */
public class systemJPanel extends javax.swing.JPanel {

    /**
     * Creates new form systemJPanel
     */
    
    private System system;
    private JPanel displayJpanel;
    
    public systemJPanel(JPanel displayJpanel, System system) {
        this.displayJpanel = displayJpanel;
        this.system = system;
        initComponents();
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        manageSystemJLabel = new javax.swing.JLabel();
        goJButton = new javax.swing.JButton();

        manageSystemJLabel.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        manageSystemJLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        manageSystemJLabel.setText("Manage System");

        goJButton.setText("Go");
        goJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                goJButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(74, 74, 74)
                        .addComponent(manageSystemJLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 530, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(299, 299, 299)
                        .addComponent(goJButton)))
                .addContainerGap(121, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(56, 56, 56)
                .addComponent(manageSystemJLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(101, 101, 101)
                .addComponent(goJButton)
                .addContainerGap(212, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void goJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_goJButtonActionPerformed
        // TODO add your handling code here:        
        CityJPanel cityJPanel = new CityJPanel(displayJpanel, system);
        displayJpanel.add("CityManagePanel", cityJPanel);
        CardLayout layout = (CardLayout) displayJpanel.getLayout();
        layout.next(displayJpanel);
    }//GEN-LAST:event_goJButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton goJButton;
    private javax.swing.JLabel manageSystemJLabel;
    // End of variables declaration//GEN-END:variables
}
