/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ui;

import java.awt.CardLayout;
import java.awt.Component;
import java.util.Date;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import model.City;
import model.CityName;
import model.System;

/**
 *
 * @author manojreddy
 */
public class viewCityJPanel extends javax.swing.JPanel {

    /**
     * Creates new form viewCityJPanel
     */
    
    private JPanel displayJPanel;
    private System system;
    private City city;
    
    public viewCityJPanel(JPanel displayJPanel, System system, City city) {
        this.displayJPanel = displayJPanel;
        this.system = system;
        this.city = city;
        initComponents();
        displayCityName();
    }

    public void displayCityName() {
        
        cityNamejComboBox.removeAllItems();
        String[] cities = CityName.getCitiesArray();
        for(String cityname:cities) {
            cityNamejComboBox.addItem(cityname);               
        }
        cityNamejComboBox.setSelectedItem(city.getCityName().name());
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        backjButton = new javax.swing.JButton();
        citiesjLabel = new javax.swing.JLabel();
        viewjButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        cityNamejComboBox = new javax.swing.JComboBox<>();

        backjButton.setText("< < Back");
        backjButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backjButtonActionPerformed(evt);
            }
        });

        citiesjLabel.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        citiesjLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        citiesjLabel.setText("View City");

        viewjButton.setText("Update");
        viewjButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewjButtonActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel1.setText("City Name : ");

        cityNamejComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cityNamejComboBoxActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addComponent(backjButton)
                        .addGap(43, 43, 43)
                        .addComponent(citiesjLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 346, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(216, 216, 216)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(42, 42, 42)
                        .addComponent(cityNamejComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(284, 284, 284)
                        .addComponent(viewjButton)))
                .addContainerGap(324, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(59, 59, 59)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(citiesjLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(backjButton))
                .addGap(63, 63, 63)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cityNamejComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(50, 50, 50)
                .addComponent(viewjButton)
                .addContainerGap(147, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void backjButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backjButtonActionPerformed
        // TODO add your handling code here:
        displayJPanel.remove(this);
        Component[] componentArray = displayJPanel.getComponents();
        CityJPanel cityJPanel = (CityJPanel) componentArray[componentArray.length-1];
        cityJPanel.initializeCities();
        CardLayout cardLayout = (CardLayout) displayJPanel.getLayout();
        cardLayout.previous(displayJPanel);
    }//GEN-LAST:event_backjButtonActionPerformed

    private void cityNamejComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cityNamejComboBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cityNamejComboBoxActionPerformed

    private void viewjButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewjButtonActionPerformed
        // TODO add your handling code here:
        String citySelected = (String) cityNamejComboBox.getSelectedItem();
        if(city.getCityName().name().equalsIgnoreCase(citySelected)){
            return;
        }
        
        List<City> cities = system.getCities();
        for(City citys:cities) {
            if(citys.getCityName().name().equalsIgnoreCase(citySelected)){
                JOptionPane.showMessageDialog(this, "City already existed. Please select another");
                return;
            }
        }
        city.setCityName(CityName.valueOf(citySelected));
        city.setLastUpdatedDate(new Date());
        JOptionPane.showMessageDialog(this, "Successfully Updated City");
    }//GEN-LAST:event_viewjButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backjButton;
    private javax.swing.JLabel citiesjLabel;
    private javax.swing.JComboBox<String> cityNamejComboBox;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton viewjButton;
    // End of variables declaration//GEN-END:variables
}
